# from https://github.com/sheerlox/sheerlox/blob/46ef977917f66c54685f0eb5ba044b602267d69b/.github/workflows/github-readme-stats.yml
name: Cache GitHub README Stats

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Update README']
    types:
      - completed

jobs:
  download-assets:
    runs-on: ubuntu-latest
    name: Download assets

    steps:
      - name: Download the stats file, dark theme
        run: curl 'https://github-readme-stats.sglavoie.vercel.app/api?username=sglavoie&count_private=true&show_icons=true&theme=gruvbox&show=prs_merged,prs_merged_percentage' -o stats-dark.svg

      - name: Download the stats file, light theme
        run: curl 'https://github-readme-stats.sglavoie.vercel.app/api?username=sglavoie&count_private=true&show_icons=true&show=prs_merged,prs_merged_percentage' -o stats-light.svg

      - name: Download the top languages file, dark theme
        run: curl 'https://github-readme-stats.sglavoie.vercel.app/api/top-langs/?username=sglavoie&layout=donut&theme=darcula&hide=c,html,css,lua,makefile,perl,roff,ruby,Vim%20Snippet&langs_count=6' -o top-langs-dark.svg

      - name: Download the top languages file, light theme
        run: curl 'https://github-readme-stats.sglavoie.vercel.app/api/top-langs/?username=sglavoie&layout=donut&hide=c,html,css,lua,makefile,perl,roff,ruby,Vim%20Snippet&langs_count=6' -o top-langs-light.svg

      - name: Upload artifacts
        uses: actions/upload-artifact@a8a3f3ad30e3422c9c7b888a15615d19a852ae32 # v3
        with:
          name: assets
          path: |
            stats-dark.svg
            stats-light.svg
            top-langs-dark.svg
            top-langs-light.svg

  push-assets:
    runs-on: ubuntu-latest
    name: Push assets
    needs: [download-assets]
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
      - uses: actions/download-artifact@9bc31d5ccc31df68ecc42ccf4149144866c47d8a # v3
        with:
          name: assets
          path: assets
      - uses: stefanzweifel/git-auto-commit-action@8756aa072ef5b4a080af5dc8fef36c5d586e521d # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore(assets): update cached GRS files'
          branch: main
          commit_user_name: github-readme-stats 🤖
          commit_user_email: actions@github.com
          commit_author: github-readme-stats 🤖 <actions@github.com>
