# from https://github.com/sheerlox/sheerlox/blob/46ef977917f66c54685f0eb5ba044b602267d69b/.github/workflows/github-readme-stats.yml
name: Cache GitHub README Stats

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Update README']
    types:
      - completed

jobs:
  download-assets:
    runs-on: ubuntu-latest
    name: Download assets

    steps:
      - name: Download the stats file, dark theme
        run: curl 'https://github-readme-stats.sglavoie.vercel.app/api?username=sglavoie&count_private=true&show_icons=true&theme=gruvbox&show=prs_merged,prs_merged_percentage' -o stats-dark.svg

      - name: Download the stats file, light theme
        run: curl 'https://github-readme-stats.sglavoie.vercel.app/api?username=sglavoie&count_private=true&show_icons=true&show=prs_merged,prs_merged_percentage' -o stats-light.svg

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: |
            stats-dark.svg
            stats-light.svg

  push-assets:
    runs-on: ubuntu-latest
    name: Push assets
    needs: [download-assets]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: assets
          path: assets
      - uses: stefanzweifel/git-auto-commit-action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: 'chore(assets): update cached GRS files'
          branch: main
          commit_user_name: github-readme-stats 🤖
          commit_user_email: actions@github.com
          commit_author: github-readme-stats 🤖 <actions@github.com>
